# Generated by Django 3.1.3 on 2020-12-24 06:26

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
