# Generated by Django 3.1.3 on 2020-12-31 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0003_ipinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipinfo',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('未审核', '未审核'), ('已审核', '已审核')], default='未审核', max_length=10, verbose_name='审核'),
        ),
        migrations.CreateModel(
            name='newshits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.news', verbose_name='新闻')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
