# Generated by Django 3.1.3 on 2021-01-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0006_auto_20210105_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cate',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterField(
            model_name='cate',
            name='name',
            field=models.CharField(max_length=20, verbose_name='分类'),
        ),
    ]
