# Generated by Django 3.1.3 on 2021-01-10 02:25

from django.db import migrations, models
import django.db.models.deletion
import sc.models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0007_auto_20210106_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='userimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('name', models.CharField(max_length=150, null=True)),
                ('img', models.ImageField(upload_to=sc.models.upload_to, verbose_name='图像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newshits',
            options={'verbose_name': '热度', 'verbose_name_plural': '热度'},
        ),
        migrations.AlterField(
            model_name='newshits',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.news', verbose_name='热度'),
        ),
    ]
