# Generated by Django 3.1.3 on 2021-01-10 03:01

from django.db import migrations, models
import sc.models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0008_auto_20210110_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='userfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('name', models.CharField(max_length=150, null=True)),
                ('file', models.FileField(upload_to=sc.models.upload_to, verbose_name='文件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '用户文件',
                'verbose_name_plural': '用户文件',
            },
        ),
        migrations.AlterModelOptions(
            name='auditimg',
            options={'verbose_name': '审核图像', 'verbose_name_plural': '审核图像'},
        ),
        migrations.AlterModelOptions(
            name='cate',
            options={'verbose_name': '内容分类', 'verbose_name_plural': '内容分类'},
        ),
        migrations.AlterModelOptions(
            name='ipinfo',
            options={'verbose_name': '访问地址', 'verbose_name_plural': '访问地址'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻内容', 'verbose_name_plural': '新闻内容'},
        ),
        migrations.AlterModelOptions(
            name='userimage',
            options={'verbose_name': '用户图像', 'verbose_name_plural': '用户图像'},
        ),
    ]
