# Generated by Django 3.1.3 on 2021-01-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0009_auto_20210110_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='大小'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='大小'),
        ),
    ]
