# Generated by Django 3.1.3 on 2021-01-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0010_auto_20210111_0910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userimage',
        ),
    ]
