# Generated by Django 3.1.3 on 2021-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0011_delete_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinfo',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='次数'),
        ),
    ]
