# Generated by Django 3.1.3 on 2021-01-12 07:26

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sc', '0013_auto_20210112_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='名称')),
                ('img', models.ImageField(upload_to='images/', verbose_name='图片')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.CharField(choices=[('无货', '无货'), ('有货', '有货')], default='有货', max_length=10, verbose_name='库存')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '产品名称',
                'verbose_name_plural': '产品名称',
            },
        ),
    ]
