# Generated by Django 3.1.3 on 2021-01-14 00:24

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0015_auto_20210112_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='图片封面'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='产品详情'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='pic/', verbose_name='产品图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='产品名称'),
        ),
    ]
