# Generated by Django 3.1.3 on 2021-01-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0017_producthits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthits',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.product', verbose_name='热度'),
        ),
    ]
