# Generated by Django 3.1.3 on 2021-01-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0018_auto_20210114_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pic/', verbose_name='产品图片'),
        ),
    ]
