# Generated by Django 3.1.3 on 2021-01-15 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sc', '0019_auto_20210114_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=150, verbose_name='留言')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='IP地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.product', verbose_name='产品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
    ]
