# Generated by Django 3.1.3 on 2021-01-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0020_msgbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pic/', verbose_name='图片封面'),
        ),
    ]
