# Generated by Django 3.1.3 on 2021-01-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0021_auto_20210116_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='图片封面'),
        ),
    ]
