# Generated by Django 3.1.3 on 2021-01-18 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0022_auto_20210116_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='productcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='类别名')),
                ('catetype', models.IntegerField(choices=[(1, '一级类别'), (2, '二级类别')], verbose_name='类目级别')),
                ('parentcate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcate', to='sc.productcate', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '产品类别',
                'verbose_name_plural': '产品类别',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc.productcate', verbose_name='分类'),
        ),
    ]
