# Generated by Django 3.1.3 on 2021-01-18 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0023_auto_20210118_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcate',
            name='catetype',
        ),
        migrations.AddField(
            model_name='productcate',
            name='is_root',
            field=models.BooleanField(default=False, verbose_name='是否是一级分类'),
        ),
        migrations.AlterField(
            model_name='productcate',
            name='parentcate',
            field=models.ForeignKey(blank=True, default=0, limit_choices_to={'is_root': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sc.productcate', verbose_name='上级分类'),
        ),
    ]
