# Generated by Django 3.1.3 on 2021-01-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0024_auto_20210118_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='productparentcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='类别名')),
            ],
            options={
                'verbose_name': '产品父类别',
                'verbose_name_plural': '产品父类别',
            },
        ),
        migrations.AlterModelOptions(
            name='productcate',
            options={'verbose_name': '产品子类别', 'verbose_name_plural': '产品子类别'},
        ),
        migrations.RemoveField(
            model_name='productcate',
            name='is_root',
        ),
        migrations.RemoveField(
            model_name='productcate',
            name='parentcate',
        ),
        migrations.AddField(
            model_name='productcate',
            name='topcate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc.productparentcate', verbose_name='父分类'),
        ),
    ]
