# Generated by Django 3.1.3 on 2021-01-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0026_productcate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcate',
            name='slug',
        ),
    ]
