# Generated by Django 3.1.3 on 2021-01-18 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0027_remove_productcate_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcate',
            options={'verbose_name': '产品类别', 'verbose_name_plural': '产品类别'},
        ),
        migrations.RemoveField(
            model_name='productcate',
            name='topcate',
        ),
        migrations.AddField(
            model_name='productcate',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc.productcate', verbose_name='自关联分类'),
        ),
        migrations.DeleteModel(
            name='productparentcate',
        ),
    ]
