# Generated by Django 3.1.3 on 2021-01-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0029_productcate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcate',
            name='slug',
        ),
    ]
