# Generated by Django 3.1.3 on 2021-01-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0030_remove_productcate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcate',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc.productcate', verbose_name='父分类'),
        ),
    ]
