# Generated by Django 3.1.3 on 2021-01-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0031_auto_20210118_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cate',
            name='pcate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc.cate', verbose_name='父分类'),
        ),
    ]
