# Generated by Django 3.1.3 on 2021-01-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0034_auto_20210122_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate',
            name='slug',
        ),
    ]
