# Generated by Django 3.1.3 on 2021-01-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0035_remove_cate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关键词'),
        ),
    ]
