# Generated by Django 3.1.3 on 2021-01-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0037_bconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bconfig',
            old_name='isaudit',
            new_name='isimgaudit',
        ),
    ]
