# Generated by Django 3.1.3 on 2021-01-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0038_auto_20210125_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgbook',
            name='status',
            field=models.CharField(choices=[('未审核', '未审核'), ('已审核', '已审核')], default='未审核', max_length=10, verbose_name='审核'),
        ),
    ]
