# Generated by Django 3.1.3 on 2021-01-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0039_msgbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bconfig',
            name='ismsgaudit',
            field=models.BooleanField(default=True, verbose_name='是否机器审核留言'),
        ),
    ]
