# Generated by Django 3.1.3 on 2021-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0040_auto_20210125_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='bconfig',
            name='isimgai',
            field=models.BooleanField(default=True, verbose_name='是否开启图像识别'),
        ),
    ]
