# Generated by Django 3.1.3 on 2021-01-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0042_userextend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userextend',
        ),
    ]
