# Generated by Django 3.1.3 on 2021-01-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0045_auto_20210127_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextend',
            options={'verbose_name': '用户扩展', 'verbose_name_plural': '用户扩展'},
        ),
        migrations.AddField(
            model_name='bconfig',
            name='islgn',
            field=models.BooleanField(default=True, verbose_name='是否开启登录'),
        ),
        migrations.AddField(
            model_name='bconfig',
            name='isreg',
            field=models.BooleanField(default=True, verbose_name='是否开启注册'),
        ),
        migrations.AddField(
            model_name='bconfig',
            name='totalsize',
            field=models.IntegerField(default='104857600', verbose_name='用户空间'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='ispublishnews',
            field=models.BooleanField(default=True, verbose_name='发布内容'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='ispublishprod',
            field=models.BooleanField(default=True, verbose_name='发布产品'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='isupfile',
            field=models.BooleanField(default=True, verbose_name='上传文件'),
        ),
    ]
