# Generated by Django 3.1.3 on 2021-01-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0046_auto_20210128_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bconfig',
            old_name='islgn',
            new_name='islogin',
        ),
        migrations.RenameField(
            model_name='bconfig',
            old_name='isreg',
            new_name='isregister',
        ),
    ]
