# Generated by Django 3.1.3 on 2021-01-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0047_auto_20210128_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='storage',
            field=models.IntegerField(default='0', verbose_name='存储空间'),
        ),
    ]
