# Generated by Django 3.1.3 on 2021-01-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0048_auto_20210128_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='filecate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='类别名')),
                ('cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc.filecate', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '文件类别',
                'verbose_name_plural': '文件类别',
            },
        ),
    ]
