# Generated by Django 3.1.3 on 2021-01-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0049_filecate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc.filecate', verbose_name='分类'),
        ),
    ]
