# Generated by Django 3.1.3 on 2021-02-18 23:44

from django.db import migrations, models
import sc.models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0050_userfile_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='userimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sc.models.upload_to, verbose_name='图像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.AlterField(
            model_name='userfile',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='文件名'),
        ),
    ]
